version: "3"
services:
  mongo1:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - ./server/dump:/dump
  server:
    build: ./server
    command: ["npm", "start"]
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - mongo1
  admin:
    build: ./admin
    command: ["npm", "start"]
    volumes:
      - ./admin:/app
      - ./admin/node_modules:/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo1
